### ISSUE TITLE
Event showing up as "all-day" instead of with time assigned

### ISSUE THREAD

**Issue by annh-st** [GCalTools/Sheets2GCal#65]
Hello, 

I am adding start and end times to every event but they are all showing up in my calendar as all day events. Please advise! 

Thank you!

**Comment by GCalToolkit** [comment]
Can you email me a screenshot of your event row and Header row so I can check the column titles? Also, which locale and language are using in the Sheet settings?

**Comment by annh-st** [comment]
Sure! 

Locale is United States (eastern time), language is english. 

Attached is the screenshot! 
![2024-09-27 08_58_47-HTP Upcoming and Due Calender - Google Sheets](https://github.com/user-attachments/assets/5e644334-06dd-44fd-b4ea-38eab4ede19b)

**Comment by GCalToolkit** [comment]
Thanks. You can't rename columns used by Sheets2GCal or it doesn't know what's what, so using "Start ET" instead of "Start Time" won't work.

Also, the Start column isn't actually in your time zone - it displays the time of the events in the event's own time zone (the "Timezone" column).

If you want, however, you can add your own "Start ET" column using the method I've explained at the bottom of this page: https://www.sheets2gcal.com/help/ in the section "Displaying Event Dates/Times in the Sheet Time Zone".

Using that method you can have your "Start ET" column showing all times at ET, then just hide the "Start Time" column when you aren't editing Start Times.

**Comment by annh-st** [comment]
This is so helpful and fixed the issue. Thank you so much!

**Comment by GCalToolkit** [comment]
My pleasure - I should probably make this clearer in the Help pop-up as it's quite a common problem!
