### ISSUE TITLE
Timed Events Not Importing with Sheets2GCal – Need Help

### ISSUE THREAD

**Issue by jeremiahmondello** [GCalTools/Sheets2GCal#69]
When I import my calendar dates, all-day events import correctly, but timed events do not. Is there a setting I might be missing? Both all-day and timed events are set to the same default visibility. I don't see any other settings that could be limiting the import. I am using Sheets2GCal, have only one calendar/email, and it is selected.

Any advice would be appreciated. Thanks!

**Comment by GCalToolkit** [comment]
Assuming you've filled in a Start Time and End Time in a format that the Sheet recognises this can happen with certain settings for the Sheet "Locale".

If the hour/minute separator is a period ' . ' instead of a colon ' : ' this can cause problems, and sometimes this issue is only visible when you double-click a cell containing the time, depending on the Format you are using for the column.

Which locale is currently configured in the Sheet Settings, and can you try switching to a similar locale?

If the locale isn't the problem please check your column headers (row 1). Have you edited this row in any way, and are you sure there's no other "Start Time" column in the Sheet?

If you can share a read-only copy of the Sheet with me (info at GCalTools dot com) I'll be able to check it to see what might be causing this problem.

If not, can you send some screenshots showing the full contents of row 1 and at least 1 other row with event data that's refusing to create a timed event?

**Comment by jeremiahmondello** [comment]
After further testing, I’ve realized it’s not just timed events that aren’t showing up. Any recently created event is missing. I can only see older recurring events that were created months or years ago.

Newly created events, whether timed, all-day, or even recently created recurring events, are not importing. I’ve checked the event details for both the working (older) events and the new ones, and they appear identical in the Google Calendar website.

To rule out a phone sync delay, I made sure to create the new events directly on the Google Calendar website, but the issue persists.

**Comment by jeremiahmondello** [comment]
I solved this issue. It was comming from my google calander account settings. I exported my calander then cleared using the delete button in my settings and and re-imported my calander now it is working. Somehow my calander was registering new entries as "Tasks" instead of "Events" doing this reset it and now I have the "Events" calander as the default.

**Comment by GCalToolkit** [comment]
I have no idea how that could happen... Sheets2GCal shouldn't be able to create tasks! Glad you've got it sorted out and please don't hesitate to contact me if you have any other problems.
